/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description The vocabulary an intent may draw on, and what each metric admits.
         *
         *     Read this before composing an intent: it is the difference between a planner that asks a
         *     valid question and one that guesses, then reads a 422 to find out.
         */
        get: operations["catalog-get_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlq/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["nlq-ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Query
         * @description Answer one question expressed in registry vocabulary, and optionally draw it.
         *
         *     The body carries an intent, never SQL: names are checked against the registry and values are
         *     bound as parameters, so a caller cannot widen what it is allowed to read. The deterministic
         *     twin of /nlq/ask, which reaches this same engine through a planned intent.
         */
        post: operations["query-run_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Accumulation
         * @description A running total that restarts at the beginning of each ``reset`` period.
         *
         *     Month-to-date is ``reset=month``; year-to-date is ``reset=year``. Only meaningful for a
         *     metric whose values may be summed across buckets — see ``MetricBase.additive``.
         */
        Accumulation: {
            /** @description The period the running total restarts within. */
            reset: components["schemas"]["Grain"];
        };
        /**
         * AccumulationRule
         * @description Which periods a running total may reset on, for one bucket grain.
         *
         *     A calendar fact, not an ordering: a week straddles a month boundary, so weekly buckets
         *     cannot reset monthly. `resets` is empty when nothing is coarser.
         */
        AccumulationRule: {
            /** @description The bucket grain the intent asks for. */
            grain: components["schemas"]["Grain"];
            /**
             * Resets
             * @description Periods a running total over that grain may reset on.
             */
            resets: components["schemas"]["Grain"][];
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Question
             * @description The user's natural-language question about the data.
             */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** @description The answer drawn, in the same shape the dashboard renders. Always null today: the orchestrator plans an intent but not yet a visual, so E3 populates it. The field is typed rather than absent so both surfaces share one contract and one <Chart>. */
            chart?: components["schemas"]["ChartSpec"] | null;
            /**
             * Narrative
             * @description Short narrative grounded strictly in the rows.
             */
            narrative: string;
            /**
             * Question
             * @description The question that was asked.
             */
            question: string;
            /** @description Rows, their column schema, and the intent the model actually ran. */
            result: components["schemas"]["ResultSet"];
        };
        /** CatalogDimension */
        CatalogDimension: {
            /**
             * Date Role
             * @description Set when this is a date, naming its role (lead, referral).
             */
            date_role?: string | null;
            /**
             * Label
             * @description Human-readable label for display.
             */
            label: string;
            /**
             * Members
             * @description Known values, when the set is closed. Else empty.
             */
            members: string[];
            /**
             * Name
             * @description Stable identifier; what an intent names.
             */
            name: string;
            /**
             * Synonyms
             * @description Natural-language aliases that resolve to it.
             */
            synonyms: string[];
        };
        /** CatalogMetric */
        CatalogMetric: {
            /**
             * Date Dimensions
             * @description The dates a time question about this metric may anchor on. More than one means an intent must name which; we never guess between date roles.
             */
            date_dimensions: string[];
            /**
             * Description
             * @description What the metric means, in business terms.
             */
            description: string;
            /** @description How the value is formatted for display. */
            format: components["schemas"]["MetricFormat"];
            /**
             * Groupable Dimensions
             * @description Every dimension this metric may be grouped or filtered by — one rule governs both. The others are not missing: they would fan out, are unrelated, or are pinned by the metric's own filter. A date dimension listed here may be grouped by, but not while `grain` is bucketing that same date.
             */
            groupable_dimensions: string[];
            /**
             * Label
             * @description Human-readable label for display.
             */
            label: string;
            /**
             * Name
             * @description Stable identifier; what an intent names.
             */
            name: string;
            /** @description Which time modifiers this metric admits. */
            supports: components["schemas"]["MetricCapabilities"];
            /**
             * Synonyms
             * @description Natural-language aliases that resolve to it.
             */
            synonyms: string[];
            /** @description How the value is composed: simple, ratio or derived. */
            type: components["schemas"]["MetricType"];
        };
        /** CatalogResponse */
        CatalogResponse: {
            /**
             * Accumulation Resets
             * @description Per bucket grain, the periods a running total may reset on.
             */
            accumulation_resets: components["schemas"]["AccumulationRule"][];
            /**
             * Dimensions
             * @description Every dimension in the model.
             */
            dimensions: components["schemas"]["CatalogDimension"][];
            /**
             * Grains
             * @description Bucket sizes an intent may request.
             */
            grains: components["schemas"]["Grain"][];
            /**
             * Metrics
             * @description Every metric, and what it can be asked.
             */
            metrics: components["schemas"]["CatalogMetric"][];
            /**
             * Relative Ranges
             * @description Windows named relative to today, resolved server-side against one date.
             */
            relative_ranges: components["schemas"]["RelativeRange"][];
        };
        /** ChartAxis */
        ChartAxis: {
            /** @description How to format tick labels; absent for categorical axes. */
            format?: components["schemas"]["MetricFormat"] | null;
            /**
             * Label
             * @description Axis heading.
             */
            label: string;
        };
        /**
         * ChartRequest
         * @description How the caller wants the answer drawn.
         *
         *     Deliberately a sibling of ``QueryIntent`` and never a field on it: an intent is
         *     visual-independent (concepts.md §2), so `resolved_intent` must never echo a chart type back
         *     and the agent's planner must never have to choose one to ask a question.
         */
        ChartRequest: {
            /** @description The visual to render this result as. */
            type: components["schemas"]["ChartType"];
        };
        /** ChartSeries */
        ChartSeries: {
            /**
             * Data
             * @description One value per entry in `categories`, in that order. `null` is a gap the renderer must break the line across, not a zero: a bucket with no rows, or the first bucket of a comparison, which has nothing before it.
             */
            data: (number | null)[];
            /** @description How to format this series' values. */
            format: components["schemas"]["MetricFormat"];
            /**
             * Name
             * @description Legend entry: the metric's label, or a dimension member.
             */
            name: string;
            /**
             * Palette Index
             * @description Zero-based categorical slot, fixed to the *entity* this series names and never to its rank or its position in this particular result. Cross-filtering a chart down to three of its channels must not repaint them, so the index is the member's position in the registry's declared `members` — a property of the model, not of the data. A comparison series repeats its primary's index.
             */
            palette_index: number;
            /** @description Whether this is the metric or its earlier window. */
            role: components["schemas"]["SeriesRole"];
        };
        /** ChartSpec */
        ChartSpec: {
            /**
             * Categories
             * @description The categorical axis: ISO period starts, or dimension members.
             */
            categories: string[];
            /**
             * Series
             * @description One entry per line or bar group.
             */
            series: components["schemas"]["ChartSeries"][];
            /**
             * Subtitle
             * @description The window actually covered, resolved from the intent. A caption, not a hint.
             */
            subtitle?: string | null;
            /**
             * Title
             * @description The metric being drawn.
             */
            title: string;
            type: components["schemas"]["ChartType"];
            x: components["schemas"]["ChartAxis"];
            y: components["schemas"]["ChartAxis"];
        };
        /**
         * ChartType
         * @description What to draw. Extending the spec is how a new visual arrives, never a new component.
         * @enum {string}
         */
        ChartType: "line" | "bar";
        /** Column */
        Column: {
            /** @description How to format the value; absent for periods and dimensions. */
            format?: components["schemas"]["MetricFormat"] | null;
            /**
             * Label
             * @description Human-readable heading.
             */
            label: string;
            /**
             * Name
             * @description Key this column takes in every row.
             */
            name: string;
            /** @description What the column is for: an axis, a value, a change. */
            role: components["schemas"]["ColumnRole"];
        };
        /**
         * ColumnRole
         * @enum {string}
         */
        ColumnRole: "period" | "dimension" | "metric" | "previous" | "delta";
        /**
         * Comparison
         * @description Measure each bucket against the previous one.
         *
         *     There is no period field: ``grain`` already says what a period is. Week-over-week is
         *     ``grain=week`` with a comparison, month-over-month is ``grain=month``. Year-over-year at
         *     monthly grain would be ``lag(value, 12)`` — an offset this shape admits the day something
         *     needs it, and nothing does yet.
         */
        Comparison: {
            /**
             * Kind
             * @description Relative change ('pct') or absolute ('change'). Left unset it is resolved from the metric's format, because the honest default differs: a count moving from 400 to 480 rose 20 percent, while a rate moving from 20% to 24% rose 4 points. Calling that second one '20 percent' is true of the ratio and misleading about the business.
             */
            kind?: ("pct" | "change") | null;
        };
        /**
         * DateRange
         * @description An explicit, inclusive date window. Either bound may be open.
         */
        DateRange: {
            /**
             * End
             * @description Latest date to include.
             */
            end?: string | null;
            /**
             * Start
             * @description Earliest date to include.
             */
            start?: string | null;
        };
        /**
         * ErrorResponse
         * @description The one error body every handler returns.
         *
         *     ``code`` is stable and machine-readable; ``detail`` is for a human and may change.
         *     ``allowed`` is what makes a 422 actionable — the agent re-plans from it and the UI names
         *     the options — so it is present whenever the vocabulary that would have been accepted is
         *     computable.
         */
        ErrorResponse: {
            /**
             * Allowed
             * @description Values that would have been accepted for that field.
             */
            allowed?: string[] | null;
            /**
             * Code
             * @description Stable machine-readable error code.
             */
            code?: string | null;
            /**
             * Detail
             * @description Human-readable explanation. Never leaks internals.
             */
            detail: string;
            /**
             * Field
             * @description The request field that was rejected.
             */
            field?: string | null;
        };
        /**
         * Grain
         * @enum {string}
         */
        Grain: "day" | "week" | "month" | "quarter" | "year";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Liveness marker; 'ok' when the API is up.
             * @constant
             */
            status: "ok";
        };
        /** MetricCapabilities */
        MetricCapabilities: {
            /**
             * Accumulate
             * @description Whether a running total is meaningful — true only when the metric's values sum across periods. A rate's do not.
             */
            accumulate: boolean;
            /**
             * Compare
             * @description Whether each bucket may be measured against the one before it. Needs a grain, which needs a date dimension this metric can reach.
             */
            compare: boolean;
        };
        /**
         * MetricFormat
         * @enum {string}
         */
        MetricFormat: "number" | "currency" | "percent" | "percent_point";
        /**
         * MetricType
         * @enum {string}
         */
        MetricType: "simple" | "ratio" | "derived";
        /** QueryIntent */
        QueryIntent: {
            /** @description Run a total that resets each period. Requires a grain. */
            accumulate?: components["schemas"]["Accumulation"] | null;
            /** @description Compare each bucket to the previous one. Requires a grain. */
            compare?: components["schemas"]["Comparison"] | null;
            /**
             * Date Dimension
             * @description Which date dimension to bucket/range on; inferred when the entity has one.
             */
            date_dimension?: string | null;
            /**
             * Date Range
             * @description An explicit date window, or one named relative to today and resolved here.
             */
            date_range?: components["schemas"]["DateRange"] | components["schemas"]["RelativeRange"] | null;
            /**
             * Filters
             * @description Dimension name to the exact value it must equal.
             */
            filters?: {
                [key: string]: string;
            };
            /** @description Bucket the date dimension by this grain (day/week/month/...). */
            grain?: components["schemas"]["Grain"] | null;
            /**
             * Group By
             * @description Dimension names to group the metric by.
             */
            group_by?: string[];
            /**
             * Metric
             * @description Registry name of the metric to compute.
             */
            metric: string;
        };
        /**
         * QueryRequest
         * @description An intent, and optionally how to draw its answer.
         *
         *     ``chart`` is a sibling of the intent and never a field on it. An intent is a question and is
         *     visual-independent (concepts.md §2); folding a chart type into it would echo presentation
         *     back through ``resolved_intent`` and force the agent's planner to pick a visual in order to
         *     ask anything at all.
         */
        QueryRequest: {
            /** @description Omit for rows only; name a type to also get a `ChartSpec`. */
            chart?: components["schemas"]["ChartRequest"] | null;
            intent: components["schemas"]["QueryIntent"];
        };
        /** QueryResponse */
        QueryResponse: {
            /** @description Present exactly when the request asked for a chart. */
            chart?: components["schemas"]["ChartSpec"] | null;
            result: components["schemas"]["ResultSet"];
        };
        /**
         * RelativeRange
         * @description A date window named relative to today, resolved once at the API boundary.
         *
         *     A closed enum rather than a free string so it lands in the OpenAPI schema: the agent can
         *     only pick a window we implement, and the dashboard does not reimplement "last 90 days"
         *     in TypeScript and disagree with us about whether it is inclusive.
         * @enum {string}
         */
        RelativeRange: "last_7_days" | "last_30_days" | "last_90_days" | "last_365_days" | "month_to_date" | "year_to_date";
        /** ResultSet */
        ResultSet: {
            /**
             * Columns
             * @description Describes each key in `rows`, in select order.
             */
            columns: components["schemas"]["Column"][];
            /** @description The intent as it was actually run: a relative window resolved to explicit dates, the inferred date dimension named, the comparison's kind decided. A caption can state the window the chart truly covers. */
            resolved_intent: components["schemas"]["QueryIntent"];
            /**
             * Rows
             * @description One row per group.
             */
            rows: {
                [key: string]: string | boolean | number | null;
            }[];
        };
        /**
         * SeriesRole
         * @enum {string}
         */
        SeriesRole: "primary" | "comparison";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "catalog-get_catalog": {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "health-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "nlq-ask": {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "query-run_query": {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
