/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Metrics */
        get: operations["metrics-list_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/{metric_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metric */
        get: operations["metrics-get_metric"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlq/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["nlq-ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /**
             * Question
             * @description The user's natural-language question about the data.
             */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** @description The structured intent the model planned from it. */
            intent: components["schemas"]["QueryIntent"];
            /**
             * Narrative
             * @description Short narrative grounded strictly in the rows.
             */
            narrative: string;
            /**
             * Question
             * @description The question that was asked.
             */
            question: string;
            /**
             * Rows
             * @description Result rows the intent produced.
             */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Liveness marker; 'ok' when the API is up.
             * @constant
             */
            status: "ok";
        };
        /**
         * MetricFormat
         * @enum {string}
         */
        MetricFormat: "number" | "currency" | "percent";
        /** MetricListResponse */
        MetricListResponse: {
            /**
             * Metrics
             * @description Metrics defined in the semantic registry.
             */
            metrics: components["schemas"]["MetricSummary"][];
        };
        /** MetricResultResponse */
        MetricResultResponse: {
            /**
             * Name
             * @description The metric that was computed.
             */
            name: string;
            /**
             * Rows
             * @description Result rows; grouped dimensions and the metric value per row.
             */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** MetricSummary */
        MetricSummary: {
            /**
             * Description
             * @description What the metric means, in business terms.
             */
            description: string;
            /** @description How the value is formatted for display. */
            format: components["schemas"]["MetricFormat"];
            /**
             * Label
             * @description Human-readable label for display.
             */
            label: string;
            /**
             * Name
             * @description Stable identifier for the metric.
             */
            name: string;
        };
        /** QueryIntent */
        QueryIntent: {
            /**
             * Filters
             * @description Dimension name to the exact value it must equal.
             */
            filters?: {
                [key: string]: string;
            };
            /**
             * Group By
             * @description Dimension names to group the metric by.
             */
            group_by?: string[];
            /**
             * Metric
             * @description Registry name of the metric to compute.
             */
            metric: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "health-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "metrics-list_metrics": {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "metrics-get_metric": {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Api-Key"?: string | null;
            };
            path: {
                metric_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "nlq-ask": {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
